import { createTool } from "@mastra/core/tools";
import z from "zod";
import {db} from '../../../lib/firebase-admin';

export const ProductSchema = z
  .object({
    id: z.string().min(1, "Product ID is required").optional(),
    sellerId: z.string().min(1, "Seller ID is required").optional(),
    title: z.string().min(1, "Product title is required"),
    description: z.string().min(1, "Description is required"),
    price: z.string().min(1, 'Price is required'),
    discount: z.string().min(1, 'Discount is required (enter 0 if no discount)'),
    currency: z.union([z.literal("$ USD"), z.literal("€ EURO"), z.literal("₦ NGN")]),
    images: z.any().array().min(1, "At least one image is required"),
    category: z.literal(["Tops","Bottoms","Dresses","Outerwear","Shoes","Accessories","Bags","Underwear","Swimwear","Activewear","Other"]),
    subCategory: z.literal([
    "T-Shirts",
    "Polo Shirts",
    "Tank Tops",
    "Blouses",
    "Dress Shirts",
    "Henleys",
    "Sweatshirts",
    "Hoodies",
    "Crop Tops",
    "Tunics",

    "Jeans",
    "Chinos",
    "Dress Pants",
    "Joggers",
    "Leggings",
    "Shorts",
    "Cargo Pants",
    "Skirts",
    "Capris",
    "Overalls",

    "Casual Dresses",
    "Evening Gowns",
    "Cocktail Dresses",
    "Maxi Dresses",
    "Mini Dresses",
    "Bodycon Dresses",
    "Wrap Dresses",
    "Shirt Dresses",
    "Sundresses",
    "Work Dresses",

    "Jackets",
    "Blazers",
    "Coats",
    "Trench Coats",
    "Parkas",
    "Bomber Jackets",
    "Leather Jackets",
    "Denim Jackets",
    "Cardigans",
    "Vests",
    
    "Sneakers",
    "Boots",
    "Sandals",
    "Loafers",
    "Heels",
    "Flats",
    "Wedges",
    "Espadrilles",
    "Oxfords",
    "Slippers",
    
    "Backpacks",
    "Tote Bags",
    "Crossbody Bags",
    "Clutches",
    "Shoulder Bags",
    "Messenger Bags",
    "Satchels",
    "Duffle Bags",
    "Belt Bags",
    "Laptop Bags",

    "Hats & Caps",
    "Scarves",
    "Gloves",
    "Belts",
    "Ties & Bowties",
    "Watches",
    "Jewelry",
    "Sunglasses",
    "Wallets",
    "Hair Accessories",

    "Boxers",
    "Briefs",
    "Trunks",
    "Bras",
    "Panties",
    "Camisoles",
    "Thermal Underwear",
    "Shapewear",
    "Bralettes",
    "Lingerie",

    "Bikinis",
    "One-Piece Swimsuits",
    "Tankinis",
    "Swim Trunks",
    "Boardshorts",
    "Rash Guards",
    "Swim Dresses",
    "Monokinis",
    "Swim Skirts",
    "Cover-Ups",

    "Gym Shorts",
    "Sports Bras",
    "Leggings",
    "Tracksuits",
    "Compression Wear",
    "Athletic T-Shirts",
    "Tank Tops",
    "Joggers",
    "Hoodies",
    "Yoga Pants",

    "Custom Wear",
    "Uniforms",
    "Costumes",
    "Maternity Wear",
    "Workwear",
    "Ethnic Wear",
    "Festival Outfits",
    "Seasonal Clothing",
    "Vintage",
    "Miscellaneous"
]),    
    condition: z.literal(["new", "used"]),
    size: z.union([
      z.literal(["One Size", "XS", "S", "M", "L", "XL", "XXL"]), // alpha + one size
      z.string().regex(/^\d+$/, "Numeric size must be digits only"), // numeric like 28, 30, 42...
    ]),
    gender: z.literal(["Men", "Women", "Unisex"]),
    brand: z.string().optional(),
    color: z.string().optional(),
    material: z.string().optional(),
    sku: z.string().optional(),
    location: z.string().optional(),
    views: z.number().optional(),
  status: z.literal(['available', 'pending', 'sold']).optional(),
  });

type ProductType = z.infer<typeof ProductSchema>;

export const getProductsTool = createTool({
    id: 'get-products',
    description: 'Get all available products on Shoppe.',
    inputSchema: z.object({}),
    outputSchema: ProductSchema.array().describe('Array of products on shoppe'),
    execute: async () => {
        const snapshot = await db.collection('products').where('status', '==', 'available').get();
        return snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })) as ProductType[];
    },

})